[commandDescriptions]
  about      = "Information about the bot"
  choose     = "Picks from a selection menu"
  discordfm  = "Plays music from discord.fm playlists"
  dump       = "Outputs the music queue as a json string"
  help       = "Shows command help"
  invite     = "Adds the bot to your server"
  jump       = "Skips to a time in the current song"
  load       = "Loads in a queue dump"
  loop       = "Repeats the whole song queue"
  move       = "Moves the bot to a different voice channel"
  nowplaying = "Shows the current song"
  pause      = "Pauses & resumes the song"
  play       = "Adds a song to the queue and begins playing"
  queue      = "Shows the song queue"
  radioplay  = "Streams radio stations"
  remove     = "Removes a song from the queue"
  reorder    = "Changes the position of a song in the queue"
  repeat     = "Loops the current song"
  restart    = "Plays a song from the beginning"
  search     = "Searches for a song on youtube"
  shuffle    = "Shuffles the song queue"
  skip       = "Plays the next song in the queue"
  soundcloud = "Searches for a song from soundcloud"
  stop       = "Stops playing and leaves the voice channel"
  volume     = "Changes the music volume"
  
  [radioStations]
  "RMF Maxxx"                        = "http://195.150.20.242:8000/rmf_maxxx"
  "RMF FM"                           = "http://31.192.216.7:8000/rmf_fm"
  "Eska Krakow"                      = "http://s3.deb1.scdn.smcloud.net/t046-1.mp3|ESKA Krak\xc3\xb3w|Pop|PL|128|0"
  "Eska Lublin"                      = "http://s3.deb1.scdn.smcloud.net/t062-1.mp3|ESKA Lublin|Pop|PL|128|0"
  "Eska Zamosc                       = "http://s3.deb1.scdn.smcloud.net/t068-1.mp3|ESKA Zamo\xc5\x9b\xc4\x87|Pop|PL|128|0"
  "Eska"                             = "http://s3.deb1.scdn.smcloud.net/t078-1.mp3|ESKA \xc5\xbbary|Pop|PL|128|0" 
  "Eska Warszawa                     = "http://s3.deb1.scdn.smcloud.net/t042-1.mp3|Eska Warszawa|Pop|PL|128|0"
